name: flutter_advanced_calendar_example
description: Demonstrates how to use the flutter_advanced_calendar plugin.

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_calendar:
    path: ../

flutter:
  uses-material-design: true
