name: flutter_advanced_calendar_example
version: 1.3.1+1
description: Demonstrates how to use the flutter_advanced_calendar plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_advanced_calendar:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
