include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    todo: warning

linter:
  rules:
    library_private_types_in_public_api: false
    unawaited_futures: false
    always_put_control_body_on_new_line: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_positional_boolean_parameters: true
    avoid_unused_constructor_parameters: true
    constant_identifier_names: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    flutter_style_todos: true
    leading_newlines_in_multiline_strings: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_in_for_each: true
    prefer_if_null_operators: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    require_trailing_commas: true
    slash_for_doc_comments: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_lambdas: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_named_constants: true
